# Generated by Django 5.2.7 on 2025-10-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
