# Generated by Django 5.2.7 on 2025-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='myauth/static/myauth/img/images.png', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
